// i18n.js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
    resources: {
        en: {
            translation: {
                "General": "Overview",
                "Propiedades": "Properties", "Propiedad": "Property",
                "Servicios": "Services",
                "Reservas": "Reservations",
                "Personal": "Staff",
                "Reseñas": "Reviews",
                "Cliente": "Client","Clientes": "Clients",
                "Buscar": "Search",
                "Titulo": "Title", "Cambiar idioma": "Change language",
                "Bienvenido": "Welcome",
                "Aquí encontraras todo los datos que necesitas para tener un negocio sumamente organizado con estadísticas": "Here you will find all the data you need to have a highly organized business with statistics",
                "Reservas Mensuales": "Monthly Reservations",
                "Precios de Apartamentos por Tipo": "Apartment Prices by Type",
                "Tipo de Propiedad": "Property Type",
                "Promedio de Precios": "Average Prices",
                "Casa": "House",
                "Cabaña": "Cabin",
                "Departamento": "Department",
                "Apartamento": "Apartment",
                "Visitas": "Visits",
                "Hora": "Hour",
                "desde las ultimas 24 horas": "since the last 24 hours",
                "Clientes mes": "Clients month",
                "Mes": "Month", "Meses": "Months",
                "Ganancias totales": "Total earnings",
                "desde el mes pasado": "since last month",
                "Reservas confirmadas": "Confirmed reservations",
                "Reservas Totales": "Total Reserves",
                "Cantidad de Reservas": "Amount of Reservations",

                "Nueva reserva confirmada": "New reservation confirmed",
                "La propiedad 'Casa Playa Sol' ha sido reservada por el cliente Juan Pérez para el 10 de diciembre...": "The property 'Casa Playa Sol' has been reserved by client Juan Pérez for December 10...",
                "Pago recibido": "Payment received",
                "Se recibió un pago de $500 por la reserva de 'Apartamento Urbano'...": "A payment of $500 has been received for the reservation of 'Urban Apartment'...",
                "Solicitud pendiente": "Pending request",
                "El cliente Ana Gómez solicitó reservar 'Villa Esmeralda'. Pendiente de aprobación...": "The client Ana Gómez requested to reserve 'Villa Esmeralda'. Pending approval...",
                "Mantenimiento programado": "Scheduled maintenance",
                "La propiedad 'Cabaña Montaña' tiene mantenimiento programado para el 15 de diciembre...": "The property 'Mountain Cabin' has scheduled maintenance for December 15...",

                "Cliente: Luis Fernández": "Client: Luis Fernández",
                "Hola, estoy interesado en la propiedad 'Casa Vista Mar'. ¿Está disponible para enero?...": "Hello, I am interested in the property 'Casa Vista Mar'. Is it available for January?...",

                "Cliente: María Torres": "Client: María Torres",
                "Buenos días, quisiera saber si puedo obtener un descuento por una reserva de 3 semanas...": "Good morning, I would like to know if I can get a discount for a 3-week reservation...",

                "Cliente: Pedro Alvarado": "Client: Pedro Alvarado",
                "Hola, intenté reservar 'Apartamento Urbano', pero el sistema no me deja avanzar...": "Hello, I tried to reserve 'Urban Apartment', but the system won't let me proceed...",

                "Cliente: Sofía Rivas": "Client: Sofía Rivas",
                "Buenas tardes, tengo dudas sobre los servicios incluidos en la 'Villa Esmeralda'...": "Good afternoon, I have questions about the services included in the 'Villa Esmeralda'...",
                "Mi Perfil": "My Profile", "Perfil": "Profile",
                "Configuración": "Configuration",
                "Ayuda": "Help",
                "Cerrar Sesión": "Logout",

                "NOMBRE": "NAME", "CLASIFICACIÓN": "CLASIFICATION", "TIPO": "TYPE", "UBICACIÓN": "LOCATION", "DISTRITO": "DISTRICT", "ESTADO": "STATE", "PRECIO": "PRICE",
                "Nombre": "Name", "Clasificación": "Clasification", "Tipo": "Type", "Ubicación": "Location",
                "Distrito": "District", "Estado": "State", "Precio": "Price",
                "Disponible": "Avaliable", "Reservado": "Reserved", "En proceso": "In process",
                "Filas a mostrar": "Rows to show",
                "Agregar": "Add", "Cancelar": "Cancel",
                "Guardar cambios": "Save Changes",
                "Editar Propiedad": "Edit Property",
                "Agregar Nueva Propiedad": "Add New Property",
                "Estado de Propiedades": "Property Status",
                "DISPONIBLES": "AVALIABLE", "RESERVADOS": "RESERVED", "EN PROCESO": "IN PROCESS",

                "Editar Servicio": "Edit Service", "Duracion": "Duration", "DURACIÓN": "DURATION",
                "Agregar Nuevo Servicio": "Add New Service",
                "Cena": "Dinner", "Almuerzo": "Lunch", "Desayuno": "Breakfast", "Uso": "Use", "Servicio": "Service",
                "Nuevo": "New", "CLIENTE": "CLIENT", "PROPIEDAD": "PROPERTY", "FECHA": "DATE",
                "En curso": "On progress", "Culminada": "Finished",
                "Editar Reserva": "Edit Reservation", "Agregar Nueva Reserva": "Add New Reservation",
                "Ene": "Jan", "Feb": "Feb", "Mar": "Mar", "Abr": "Apr", "May": "May", "Jun": "Jun", "Jul": "Jul",
                "Ago": "Aug", "Sep": "Sep", "Oct": "Oct", "Nov": "Nov", "Dic": "Dec",
                "CARGO":"CHARGE","DESDE":"FROM","HASTA":"TO","CULMINACIÓN":"CULMINATION",
                "Cargo":"Charge","Desde":"From","Hasta":"To",
                "Editar Personal":"Edit Staff",
                "Agregar Nuevo Personal":"Add New Staff",
                "empleado":"employee","supervisor":"supervisory","gerente":"manager","contador":"counter",
                "Contrato finalizado":"Contract finished",
                "meses": "{{count}} months",
                "Número de Personal por Cargo":"Number of Personnel by Position",
                "Cantidad":"Amount","CONTEO":"COUNT",
                "Número":"Number",
                "Fecha de Registro":"Registration Date",
                "Editar Cliente":"Edit Client",
                "Agregar Nuevo Cliente":"Add New Client",
                "Cantidad de Clientes":"Clients Amount",
                "Clientes Mensuales":"Monthly Clients",
                "Clientes nuevos por mes":"New clients per month", 
                "Negocio":"Business",
                "Para Ti":"For You",
            },
        },
        es: {
            translation: {
                "Overview": "General",
                "Propiedades": "Propiedades", "Propiedad": "Propiedad",
                "Servicios": "Servicios", "Servicio": "Servicio",
                "CLIENTE": "CLIENTE", "PROPIEDAD": "PROPIEDAD", "FECHA": "FECHA",
                "Reservas": "Reservas",
                "Personal": "Personal", "Nuevo": "Nuevo",
                "Reseñas": "Reseñas",
                "Cliente": "Cliente",
                "Buscar": "Buscar",
                "Titulo": "Titulo", "Cambiar idioma": "Cambiar idioma",
                "Bienvenido": "Bienvenido",
                "Aquí encontraras todo los datos que necesitas para tener un negocio sumamente organizado con estadísticas": "Aquí encontraras todo los datos que necesitas para tener un negocio sumamente organizado con estadísticas",
                "Reservas Mensuales": "Reservas Mensuales",
                "Precios de Apartamentos por Tipo": "Precios de Apartamentos por Tipo",
                "Tipo de Propiedad": "Tipo de Propiedad",
                "Promedio de Precios": "Promedio de Precios",
                "Casa": "Casa",
                "Cabaña": "Cabaña",
                "Departamento": "Departamento",
                "Apartamento": "Apartamento",
                "Visitas": "Visitas",
                "Hora": "Hora",
                "desde las ultimas 24 horas": "desde las ultimas 24 horas",
                "Clientes mes": "Clientes mes",
                "Mes": "Mes", "Meses": "Meses",
                "Ganancias totales": "Ganancias totales",
                "desde el mes pasado": "desde el mes pasado",
                "Reservas confirmadas": "Reservas confirmadas",
                "Reservas Totales": "Reservas Totales",
                "Cantidad de Reservas": "Cantidad de Reservas",

                "Nueva reserva confirmada": "Nueva reserva confirmada",
                "La propiedad 'Casa Playa Sol' ha sido reservada por el cliente Juan Pérez para el 10 de diciembre...": "La propiedad 'Casa Playa Sol' ha sido reservada por el cliente Juan Pérez para el 10 de diciembre...",
                "Pago recibido": "Pago recibido",
                "Se recibió un pago de $500 por la reserva de 'Apartamento Urbano'...": "Se recibió un pago de $500 por la reserva de 'Apartamento Urbano'...",
                "Solicitud pendiente": "Solicitud pendiente",
                "El cliente Ana Gómez solicitó reservar 'Villa Esmeralda'. Pendiente de aprobación...": "El cliente Ana Gómez solicitó reservar 'Villa Esmeralda'. Pendiente de aprobación...",
                "Mantenimiento programado": "Mantenimiento programado",
                "La propiedad 'Cabaña Montaña' tiene mantenimiento programado para el 15 de diciembre...": "La propiedad 'Cabaña Montaña' tiene mantenimiento programado para el 15 de diciembre...",

                "Cliente: Luis Fernández": "Cliente: Luis Fernández",
                "Hola, estoy interesado en la propiedad 'Casa Vista Mar'. ¿Está disponible para enero?...": "Hola, estoy interesado en la propiedad 'Casa Vista Mar'. ¿Está disponible para enero?...",

                "Cliente: María Torres": "Cliente: María Torres",
                "Buenos días, quisiera saber si puedo obtener un descuento por una reserva de 3 semanas...": "Buenos días, quisiera saber si puedo obtener un descuento por una reserva de 3 semanas...",

                "Cliente: Pedro Alvarado": "Cliente: Pedro Alvarado",
                "Hola, intenté reservar 'Apartamento Urbano', pero el sistema no me deja avanzar...": "Hola, intenté reservar 'Apartamento Urbano', pero el sistema no me deja avanzar...",

                "Cliente: Sofía Rivas": "Cliente: Sofía Rivas",
                "Buenas tardes, tengo dudas sobre los servicios incluidos en la 'Villa Esmeralda'...": "Buenas tardes, tengo dudas sobre los servicios incluidos en la 'Villa Esmeralda'...",
                "Mi Perfil": "Mi Perfil", "Perfil": "Perfil",
                "Configuración": "Configuración",
                "Ayuda": "Ayuda",
                "Cerrar Sesión": "Cerrar Sesión",

                "NOMBRE": "NOMBRE", "CLASIFICACIÓN": "CLASIFICACIÓN", "TIPO": "TIPO", "UBICACIÓN": "UBICACIÓN", "DISTRITO": "DISTRITO", "ESTADO": "ESTADO", "PRECIO": "PRECIO",
                "Nombre": "Nombre", "Clasificación": "Clasification", "Tipo": "Type", "Ubicación": "Location",
                "Distrito": "District", "Estado": "State", "Precio": "Price",
                "Disponible": "Disponible", "Reservado": "Reservado", "En proceso": "En proceso",
                "Filas a mostrar": "Filas a mostrar",
                "Agregar": "Agregar", "Cancelar": "Cancelar",
                "Guardar Cambios": "Guardar Cambios",
                "Editar Propiedad": "Editar Propiedad",
                "Agregar Nueva Propiedad": "Agregar Nueva Propiedad",
                "Estado de Propiedades": "Estado de Propiedades",
                "DISPONIBLES": "DISPONIBLES", "RESERVADOS": "RESERVADOS", "EN PROCESO": "EN PROCESO",

                "Editar Servicio": "Editar Servicio", "Duracion": "Duracion", "DURACIÓN": "DURACIÓN",
                "Agregar Nuevo Servicio": "Agregar Nuevo Servicio",
                "Cena": "Cena", "Almuerzo": "Almuerzo", "Desayuno": "Desayuno", "Uso": "Uso",
                "Ene": "Ene", "Feb": "Feb", "Mar": "Mar", "Abr": "Abr", "May": "May", "Jun": "Jun", "Jul": "Jul",
                 "Ago": "Ago", "Sep": "Sep", "Oct": "Oct", "Nov": "Nov", "Dic": "Dic",
                
                 "CARGO":"CARGO","DESDE":"DESDE","HASTA":"HASTA","CULMINACIÓN":"CULMINACIÓN",
                 "Cargo":"Cargo","Desde":"Desde","Hasta":"Hasta",
                 "Editar Personal":"Editar Personal",
                 "Agregar Nuevo Personal":"Agregar Nuevo Personal",
                 "empleado":"empleado","supervisor":"supervisor","gerente":"gerente","contador":"contador",
                "Contrato finalizado":"Contrato finalizado",
                "meses": "{{count}} meses",
                "Número de Personal por Cargo":"Número de Personal por Cargo",
                "cantidad":"cantidad","CONTEO":"CONTEO",
                "Clientes":"Clientes",
                "Número":"Número",
                "Fecha de Registro":"Fecha de Registro",
                "Cantidad de Clientes":"Cantidad de Clientes",
                "Clientes Mensuales":"Clientes Mensuales",  
                "Clientes nuevos por mes":"Clientes nuevos por mes",
                "Negocio":"Negocio",
                "Para Ti":"Para Ti",
            },
        },
    },
    lng: "es", // Idioma predeterminado
    fallbackLng: "es",
    interpolation: {
        escapeValue: false,
    },
});

export default i18n;
